### ISSUE TITLE
accusing thoratica

### ISSUE THREAD

**Issue by noamboy2006** [thoratica/Share-Images#1]
![image](https://user-images.githubusercontent.com/32446774/80218809-9dd0e080-867c-11ea-9f0d-2f1e6ecf24fc.png)
The developer of this project,thoratica is threatening me to press star.
And, he is constantly erasing all the images.
LOL

**Comment by thoratica** [comment]
I was just asking 'how about pressing the star?'.
+ gangjun06 was spamming....

**Comment by noamboy2006** [comment]
> I was just asking 'how about pressing the star?'.
> + gangjun06 was spamming....

That's A bad answer...
I'm dissapointed.
I will punish you by pressing a star OTL.

**Comment by gangjun06** [comment]
hmm...

**Comment by thoratica** [comment]
Thank you for punishing!
